### ISSUE TITLE
Missing lsd_slam setting

### ISSUE THREAD

**Issue by grotli** [alexanderkoumis/lsd_slam_to_pcl#3]
Hi! I am not able to get this work, see the following message:

[ INFO] [1490882912.427715206]: waitForService: Service [/nodelet_manager/load_nodelet] has not been advertised, waiting...

I believe that this has to do with wrong lsd_slam setting? What do I have to do to get this to work?
Do I need to set "continuousPCOutput" to true in LSDDebugParams.cfg and set(CMAKE_BUILD_TYPE RelWithDebInfo) in CMakeList.txt ? I have already tried this, but still nothing happens.

**Comment by alexanderkoumis** [comment]
Hi, it's been a while since I've worked on this package. I'll try to get something running in the next couple of days and address your issue.

**Comment by heimagithub** [comment]
Hi! I have the same problem. I would ask problem that how to use lsd_slam_to_pcl? Is write a launch file only like below?? 

https://ibb.co/kN1DLk

if no problem. I meet the same problem for "... waitForService: Service [/nodelet_manager/load_nodelet] has not been advertised, waiting..."   

or If something wrong at my launch file??

**Comment by 0w0miki** [comment]
You should launch a nodelet manager named `nodelet_manager` first. 
Open a terminal and run
```
rosrun nodelet nodelet manager __name:=nodelet_manager
```
and then launch the launch file, or you can add a line in the launch file just before the given example
```
<node pkg="nodelet" type="nodelet" name="nodelet_manager"  args="manager"/>
```

**Comment by alexanderkoumis** [comment]
Thanks @0w0miki. I added a full launchfile example in the readme.
